{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rutherford.serviceAccountName" . }}
  labels:
    {{- include "rutherford.labels" . | nindent 4 }}
{{- end }}
