apiVersion: v1
kind: Service
metadata:
  name: {{ include "rutherford.fullname" . }}
  labels:
    {{- include "rutherford.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "rutherford.selectorLabels" . | nindent 4 }}
